### ISSUE TITLE
Critical Issue

### ISSUE THREAD

**Issue by Tnology** [Zacknac/zacknac.github.io#1]
Hello Zacknac, 

It appears that you are the author of this project. I am creating this to inform you of a critical issue with your project **zacknac.github.io**. The critical issue in question is that your readme file is called `index.md` rather than `README.md`. This is a problem because it means that a user must click the `index.md` file to read the markdown file containing the necessary information about this important project.

It is first important to know what a README is. A README file allows you to tell the other people viewing your project the information about your project, as well as what they can do with it, and why your amazing project is super useful. Your index.md file contains quite important information about this project, which has changed the way that we see software thanks to your hard work. Having the information of the README be seen by default from the markdown file is quite important, because it means that people are more likely to see information about your work of art of a project.

I hope you understand why I am creating this GitHub issue. This is a critical issue that should be resolved immediately. I hope you take the time to consider working on the fix for this, although I also hope that this will not be too difficult to do. I understand it may be hard to perform the process of renaming a file, though - it's probably about as hard as getting humans to live on Pluto, creating infinite water on Earth, getting Blocks_n_more to like Python, or even centering a div. I believe in your abilities to overcome this obstacle in making this difficult change, however. 

Thank you for your time, 
T_nology

**Comment by Zacknac** [comment]
get life nerd
